### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [ieb/WindSensor#1]
Hi, I noticed that you wait after a Wire.requestFrom(), in the file WindSensor/lib/as5600/as5600.cpp:
```
while(Wire.available() == 0);
```
However, there is nothing to wait for.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by ieb** [comment]
Thank you for spotting it, I will fix.
